version: '3.4'

services:
  postgres-db:
    container_name: 'postgres-db'
    image: postgres
    restart: always
    networks:
      - local-network

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - "postgres-db"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge